### ISSUE TITLE
 Accept clinical update event from Kafka

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#25]
- This ticket is just to have files-service consume the event.
- We can trigger the existing process to update the given fils for the appropriate donors.

**Comment by b-f-chan** [comment]
@mistryrn to complete before moving onto new HCMI maintenance contract work week of Apr 25

**Comment by b-f-chan** [comment]
@mistryrn has this gone to PR review?  I see it in review column but can't find actual PR - Thanks!
