### ISSUE TITLE
API to reindex whole repository (on-demand)

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#41]
Index a repository manually on demand 

- endpoint in file-service and it will index an entire Song on command 
- takes repository code  

Require RDPC to be reachable by Platform. 

Kafka events contain the Song analysis, but we don't want to rely on Kafka reply for indexing.  
- We will reach out to the Song and queue the analysis in a reindex topic that files-service will listen to. 
- response with a list of analysis to enqueue 
- partition topic to allow parallelization and fat processing (partition by program-id key)

**Comment by blabadi** [comment]
for testing/demo:

use this api
- https://files.qa.argo.cancercollaboratory.org/api-docs/#/default/post_admin_index__datacenter_
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/709653eb-4802-4fe6-9d9f-8d407985fd2d)

- use `song.collab` as data center

- currently there is no notification of when indexing is done, but it needs at least 10 mins as of right now, there is room of improvement by study level parallelization
