### ISSUE TITLE
Design: Index Clinical Data with file data 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#56]
- Setup connection to clinical DB
- `file-manager` should index clinical data that belongs to the donor of a file into the index(s)
- When a file is indexed, the clinical data for that donor is also included in the documents

## Expected Outcome
- working session to create a design / plan for work that needs to be done. 
- Design wiki / diagram if needed. 

### UPDATE 12/22/21
Following a design session with Jon, the following Wiki page has been created detailing the work necessary to implement this feature: https://wiki.oicr.on.ca/display/icgcargotech/Connecting+the+File+Manager+to+Clinical+Data

**Comment by mistryrn** [comment]
Wiki page detailing the work needed for this: https://wiki.oicr.on.ca/display/icgcargotech/Connecting+the+File+Manager+to+Clinical+Data

**Comment by akachru-github** [comment]
Pending decision on whether or not clinical DB will be accessed directly, or whether a clinical API should be implemented.

**Comment by akachru-github** [comment]
@mistryrn and @joneubank , I think we can add the proposed Clinical API to the diagram in the wiki and close this ticket!
