### ISSUE TITLE
Implement dcc admin authorization 

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/files-service#6]
- File-service endpoints to write need to be protected
![image.png](https://images.zenhubusercontent.com/5a06111e8a75884b9086f5d8/78b25051-1f30-47d6-97f6-d37cfe3adf7f)

- Add a new policy 
- Add the policy to the dcc-admin group

## Expected outcome 
- Cannot query endpoint in swagger without auth 
- Can query endpoints when correct scope is added.

**Comment by rosibaj** [comment]
tested on qa - auth was required for endpoints.
