### ISSUE TITLE
🐛 Timeout when trying to promote a donor to "public" release

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#68]
### Command (through swagger)
```
curl -X POST "https://files.qa.argo.cancercollaboratory.org/admin/promote/PUBLIC?dryRun=false" -H  "accept: application/json" -H  "Authorization: Bearer [EGO JWT HERE]" -H  "Content-Type: application/json" -d "{\"include\":{\"donors\":[\"DO262418\"]}}"

```

### Response: 
![image](https://user-images.githubusercontent.com/15824252/124192899-07742800-da94-11eb-9f72-2cef013ca1a6.png)

### Checking the active release, 
it looks like they did in fact get added though. 
![image](https://user-images.githubusercontent.com/15824252/124193200-6cc81900-da94-11eb-8e7c-a736ec05e2b5.png)

## Expected Behaviour.  
If the endpoint works, it should not be followed by a timeout.

**Comment by joneubank** [comment]
The release process has been re-worked and now is all async. This will no longer occur.
