### ISSUE TITLE
Recurring job (nightly) to promote files in emarbgo stages

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/files-service#85]
- [ ] For each file, read the `firstPublishedDate` and promote it through the stages

- Consider job management infrastructure to support upcoming jobs that fall into this category. Anticipating more jobs like this will com about. 
- Logic for changing categories and indexing already exists.

**Comment by joneubank** [comment]
File service now has an internal process to complete this activity. It can be triggered manually through an admin API, and is also listening to a kafka topic to trigger this job to run.

I am in the process of adding a cron-job to kubernetes that will inject a message into this queue nightly. Details to follow when available.

**Comment by joneubank** [comment]
This cron job should not be run until the updated embargo rules are added.

https://github.com/icgc-argo/files-service/issues/123

**Comment by b-f-chan** [comment]
Testing not required, but we do not want this in prod yet, will move to ready to release at appropriate time when we're ready to consume it

**Comment by b-f-chan** [comment]
@joneubank to tag with correct version label

**Comment by Buwujiu** [comment]
@joneubank let's do a demo tomorrow and then move it to awaiting release.
